<a href="https://colab.research.google.com/github/alaplace17/DS1002_Alexander_Laplace/blob/main/07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [199]:
# Load pandas and the data
import pandas as pd
import numpy as np

In [200]:
# show how many rows and columns are in this dataset
ride_sharing_loaded = pd.read_csv('/content/ride_sharing.csv')
ride_sharing_loaded.head(5)

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27

In [201]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
ride_sharing_loaded['duration'] = ride_sharing_loaded['duration'].str.strip('minutes')
ride_sharing_loaded['duration'] = ride_sharing_loaded['duration'].astype('int')

In [202]:
# Now display the datatypes in the updated dataframe
ride_sharing_loaded.dtypes

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [203]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
print("The shortest ride time was ",ride_sharing_loaded['duration'].min(), " minute/s.")
print("The longest ride time was ",ride_sharing_loaded['duration'].max(), " minute/s.")

The shortest ride time was  1  minute/s.
The longest ride time was  1372  minute/s.

In [204]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
filtered_df_hour = ride_sharing_loaded.query("duration <= 60")
filtered_df_hour.head(10)

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
5,10,22,Howard St at Beale St,6,The Embarcadero at Sansome St,3279,2,1979,Male,29
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
7,9,30,San Francisco Caltrain (Townsend St at 4th St),97,14th St at Mission St,5286,2,1991,Male,27
8,21,81,Berry St at 4th St,16,Steuart St at Market St,2124,1,1982,Female,29
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26

In [205]:
# Now show both the min and max values of the duration column for your new dataset.
print("The shortest ride time for the new dataset was ",filtered_df_hour['duration'].min(), " minute/s.")
print("The longest ride time for the new dataset was ",filtered_df_hour['duration'].max(), " minute/s.")

The shortest ride time for the new dataset was  1  minute/s.
The longest ride time for the new dataset was  60  minute/s.

In [206]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
filtered_df_hour_tire = filtered_df_hour.query("tire_size == 26")
filtered_df_hour_tire.head(6)

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
15,4,3,Powell St BART Station (Market St at 4th St),321,5th St at Folsom,1606,2,1995,Male,26

In [207]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.

value_count = filtered_df_hour_tire['user_gender'].value_counts()['Female']
print(value_count)

2962

2. Find the file `more-messy-data.csv` on GitHub and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [208]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
more_messy_data = pd.read_csv('/content/more-messy-data.csv')
print(more_messy_data.duplicated().sum())

287

In [209]:
# Next, remove all duplicate rows using Python.
more_data = more_messy_data.drop_duplicates()
more_data.tail(100)

       id  sepal_length  sepal_width  petal_length petal_width     species
929   930           3.9          3.2           1.4         1.6   virginica
930   931           3.8          2.6           1.4         0.8   virginica
931   932           5.4          2.5           1.4         0.9      setosa
932   933           4.0          3.1           2.6         2.3      setosa
933   934           3.7          3.3           2.6         NaN   virginica
...   ...           ...          ...           ...         ...         ...
1311  412           NaN          3.6           2.9         0.5  Versicolor
1312  413           5.8          2.7           2.0         0.1  Versicolor
1313  414           3.3          3.7           1.3         2.8  Versicolor
1314  415           3.1          NaN           1.1         NaN  Versicolor
1315  416           4.3          2.5           1.3           1  Versicolor

[100 rows x 6 columns]

In [210]:
more_data['petal_width'] = pd.to_numeric(more_data['petal_width'], errors='coerce')

<ipython-input-210-12c4fbf75846>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_data['petal_width'] = pd.to_numeric(more_data['petal_width'], errors='coerce')

In [211]:
more_data['petal_width'] = more_data['petal_width'].astype(float)
more_data.dtypes

<ipython-input-211-5318919fbec4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_data['petal_width'] = more_data['petal_width'].astype(float)

id                int64
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [212]:
columns_to_impute = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

for column in columns_to_impute:
    mean_value = more_data[column].mean()
    more_data[column].fillna(mean_value, inplace=True)

<ipython-input-212-bf2bb7ba6ca0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_data[column].fillna(mean_value, inplace=True)

In [214]:
# Find any values in the dataframe that are still missing, and delete them.
cleaned_data = more_data.dropna(subset=['species'])

In [216]:
missing_counts = cleaned_data.isna().sum()
print(missing_counts)

id              0
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [227]:
# Clean up the 'species' variable so that there are exactly three different values.
cleaned_data['species'] = cleaned_data['species'].str.lower()

<ipython-input-227-08cf6e01ab12>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['species'] = cleaned_data['species'].str.lower()

In [228]:
# How many different species are there?
unique_species_values = cleaned_data['species'].unique()
print(unique_species_values)

['virginica' 'setosa' 'versicolor' 'setoso' 'viginica' 'virginia'
 'setosan']

There are 3 different species but 7 different variables bc of misspelling now after dealing with capitalized species names meaning some cleaning must be done.

In [ ]:
# Clean up the 'species' variable so that there are exactly three different values.
correct_values = {'viginica':'virginica', 'virginia':'virginica', 'setoso':'setosa', 'setosan':'setosa'}
cleaned_data['species'] = cleaned_data['species'].replace(correct_values)

In [230]:
unique_species_values = cleaned_data['species'].unique()
print(unique_species_values)

['virginica' 'setosa' 'versicolor']

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [ ]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'aabbbc'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
# print(type(re.match(exp,test)))

# uncomment this line if you want
# print(bool(re.match(exp,test)))